create table PRODUCTOS(
	ID INT not null identity(1,1) primary key, 
	NOMBRE VARCHAR (50),
	CODIGO VARCHAR (20),
	FECHACREACION DATETIME DEFAULT GETDATE()
)

CREATE TABLE	 CLIENTES(
	ID INT not null identity(1,1) primary key, 
	NOMBRE VARCHAR (25),
	APELLIDO VARCHAR (25),
	EMAIL VARCHAR (50),
	FECHACREACION DATETIME DEFAULT GETDATE()
)

CREATE TABLE GUIAS(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_PRODUCTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	PESO DECIMAL(18,3),
	CANTIDAD INT,
	FECHACREACION DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_GUIAS_PRODUCTOS FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
	CONSTRAINT FK_GUIAS_CLIENTES FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID)
)


INSERT INTO PRODUCTOS(NOMBRE,CODIGO) 
VALUES
('ROSAS ROJAS TALLO CORTO','R0001'),
('ROSAS ROJAS TALLO LARGO','R0002'),
('ROSAS BLANCAS TALLO CORTO','R0003'),
('ROSAS BLANCAS TALLO LARGO','R0004'),
('ANTURIOS GRANDES AMARILLOS','A0002'),
('ANTURIOS ENANOS AMARILLOS','A0003');

INSERT INTO CLIENTES(NOMBRE,APELLIDO,EMAIL)
VALUES
('CARLOS JOSE','MEDINA',' CMEDINA@GMIAL.COM'),
('PEDRO','LATA',' PLA1978@GMIAL.COM'),
('ARTURO','SUAREZ',' SUAREZA145@GMIAL.COM'),
('ANIBAL','ROMERO',' ANIBAL@GMIAL.COM');


